### ISSUE TITLE
Add setting to disable autoformatting of certain characters

### ISSUE THREAD

**Issue by jbom1** [flavea/BBCode-Live-Editor#4]
Currently, the editor always replaces straight quotes ("") with curved quotes (“ ”), triple period (...) with ellipsis (…), double hyphen (--) with em dash (—), etc. This behavior can be helpful, but it is sometimes undesired. It would be nice if there were a setting to disable the autoformatting and keep exactly the characters you type.

**Comment by flavea** [comment]
Noted! I'll work on it once I have the time, thank you for the suggestion!!

**Comment by flavea** [comment]
Setting to disable autoformatting had been added
